---
title: "DA-49"
author: "Zelimkhan"
date: "2025-08-02"
output: html_document
---
# Install and attach necessary packages

```{r}
# install.packages("readxl")
# install.packages("tidyverse")
# install.packages("lubridate")
# install.packages("psych")
install.packages("stringr")
library(readxl)
library(tidyverse)
library(dplyr)
library(lubridate)
library(psych)
library(stringr)
```
# Read data
```{r}
source_df <- read_xlsx("/Users/zelimkhan/Desktop/Data/Data_sets/DA-49/2025.07.31_ DA-49_purchases_23-25_source_data_23-35_cleaned.xlsx")
head(source_df)
```

# Process data
```{r}
df <- source_df
factor_vars <- c("ИД заказчика", "Краткое название заказчика", "ГРБС", "Статус контракта", "Закон-основание", "Год заключения контракта",
         "Месяц заключения контракта", "Метод определения поставщика", "Признак закупки у единственного поставщика", "Основание закупки у ед. поставщика",
         "Признак закупки малого объема", "Признак \"Портал поставщиков\" по тексту", "Признак котировочной сессии",
         "Признак стандартизированного контракта (мин)", "Признак стандартизированного контракта (макс)", 
         "Признак НМЦ за единицу в лоте (0 - нет , 1 - да)", "Стандартизированный СПГЗ", "Метод расчета НМЦ",
         "Признак прохождения экспертизы")
df[, c(factor_vars)] <- lapply(df[, c(factor_vars)], as.factor)

datetime_vars <- c("Дата заключения контракта", "Начало действия контракта", "Начало исполнения контракта", "Конец действия контракта","Конец исполнения контракта")
df[, c(datetime_vars)] <- lapply(df[, c(datetime_vars)], ymd)

numeric_vars <- select(df, where(is.numeric)) %>% colnames() %>% c(., "Количество участников торгов, шт.")
df[, numeric_vars] <- lapply(df[, numeric_vars], as.numeric)
paste0('"', colnames(df), '"', collapse = ", ") %>% cat

df <- df %>% 
  select("ИД заказчика", "Краткое название заказчика" , "ГРБС", "Название контракта", "Статус контракта", "Стоимость контракта, руб.", "Закон-основание", "Дата заключения контракта", "Год заключения контракта", "Месяц заключения контракта", "Начало действия контракта", "Начало исполнения контракта", "Конец действия контракта", "Конец исполнения контракта", "ИД контракта", "URL контракта", "Ссылка на контракт в ЕИС", "Номер контракта в ЕИС", "Метод определения поставщика", "Признак закупки у единственного поставщика", "Основание закупки у ед. поставщика", "Признак закупки малого объема", "Признак \"Портал поставщиков\" по тексту", "Признак котировочной сессии", "Признак стандартизированного контракта (мин)", "Признак стандартизированного контракта (макс)", "ИД лота", "Количество контрактов в лоте, шт.", "Стоимость контрактов в лоте, руб.", "НМЦ лота, руб.", "Признак НМЦ за единицу в лоте (0 - нет , 1 - да)", "ИД цепочки КПГЗ", "ИД КПГЗ", "Код КПГЗ", "Последнее название цепочки КПГЗ", "Название КПГЗ", "ИД цепочки СПГЗ", "ИД СПГЗ", "Последнее название цепочки СПГЗ", "Название СПГЗ", "Ед. измерения СПГЗ", "Объем СПГЗ, ед. изм.", "Цена за единицу СПГЗ, руб.", "Сумма по СПГЗ, руб.", "Стандартизированный СПГЗ", "Метод расчета НМЦ", "ИД ПЦП", "Краткое название поставщика", "Снижение в ходе торгов (0.01 = 1%)", "Общий процент снижения (0.01 = 1%)","Количество участников торгов, шт.")
colnames(df) %>% str
remove(factor_vars, datetime_vars, numeric_vars)
glimpse(df)
```

# Analyse data
## Descreptive statistics
```{r, include=FALSE}
summary(df)
aggregate(df$`Цена за единицу СПГЗ, руб.`, by = list(source_df$ГРБС), mean)
describe(df, na.rm = T)
```
xxx
```{r}
df %>% group_by(`ГРБС`) %>% 
  summarise(contract_number = n_distinct(`ИД контракта`)) %>% arrange(desc(contract_number))

```

xxx
```{r}
df %>% group_by(`Краткое название заказчика`) %>% 
  summarise(contract_number = n_distinct(`ИД контракта`)) %>% arrange(desc(contract_number))
```

xxx
```{r}
df %>% filter(`Метод определения поставщика` == "Электронный аукцион") %>% 
  select(`Краткое название заказчика`, `ГРБС`, `Метод определения поставщика`, `ИД контракта`) %>% 
  summarise(auction_number = n_distinct(`ИД контракта`))
```
ххх
xxx
```{r}
df %>% filter(`Метод определения поставщика` %in% c("Электронный аукцион", "Электронный запрос предложений",
                                                    "Электронный конкурс", "Электронный запрос котировок")) %>% 
  select(`Краткое название заказчика`, `ГРБС`, `Метод определения поставщика`, `ИД контракта`) %>% 
  group_by(`Краткое название заказчика`) %>% 
  summarise(comp_procedure_number = n_distinct(`ИД контракта`)) %>% arrange(desc(comp_procedure_number))
```
xxx
```{r}
df %>% filter(`Метод определения поставщика` %in% c("Электронный аукцион", "Электронный запрос предложений",
                                                    "Электронный конкурс", "Электронный запрос котировок")) %>% 
  group_by(`Последнее название цепочки СПГЗ`, `ИД цепочки СПГЗ`) %>% 
  summarise(spgz = length(`Последнее название цепочки СПГЗ`)) %>% 
  arrange(desc(spgz))
```
xxx
```{r}
df %>% filter(`Метод определения поставщика` %in% c("Электронный аукцион", "Электронный запрос предложений",
                                                    "Электронный конкурс", "Электронный запрос котировок")) %>% 
  group_by(`Последнее название цепочки СПГЗ`, `ИД цепочки СПГЗ`) %>% 
  summarise(spgz = length(`Последнее название цепочки СПГЗ`),
            min_cost_one_spgz = min(`Цена за единицу СПГЗ, руб.`),
            max_cost_one_spgz = max(`Цена за единицу СПГЗ, руб.`),
            mean_cost_one_spgz = mean(`Цена за единицу СПГЗ, руб.`),
            sd_cost_one_spgz = sd(`Цена за единицу СПГЗ, руб.`)
                                      ) %>% 
  arrange(desc(spgz))
```

