library(psych)
library(googlesheets4)
library(tidyr)
library(dplyr)
library(janitor)
library(ggplot2)
library(lubridate)
library(purrr)
library(GGally)
library(readxl)
library(writexl)
library(stringr)
library(vroom)

df <- read.csv("C:/Users/GudievZK/Desktop/DataAnalysis/DA-54/2025.12.04_spgz_kpgz_ktru_db_ktlg.csv", fileEncoding = "Windows-1251")
df <- clean_names(df)
names(df)
glimpse(df)
str(df)
sapply(df, class)
colSums(is.na(df))

df_without_id_entity_spgz_eaist <- df %>% filter(is.na(id_entity_spgz_eaist))
sapply(df, function(x) sum(duplicated(x)))
